from ome_types._autogenerated.ome_2016_06.affine_transform import (
    AffineTransform,
)
from ome_types._autogenerated.ome_2016_06.annotation import Annotation
from ome_types._autogenerated.ome_2016_06.annotation_ref import AnnotationRef
from ome_types._autogenerated.ome_2016_06.arc import Arc
from ome_types._autogenerated.ome_2016_06.arc_type import Arc_Type
from ome_types._autogenerated.ome_2016_06.basic_annotation import (
    BasicAnnotation,
)
from ome_types._autogenerated.ome_2016_06.bin_data import BinData
from ome_types._autogenerated.ome_2016_06.bin_data_compression import (
    BinData_Compression,
)
from ome_types._autogenerated.ome_2016_06.binary_file import BinaryFile
from ome_types._autogenerated.ome_2016_06.binning import Binning
from ome_types._autogenerated.ome_2016_06.boolean_annotation import (
    BooleanAnnotation,
)
from ome_types._autogenerated.ome_2016_06.channel import Channel
from ome_types._autogenerated.ome_2016_06.channel_acquisition_mode import (
    Channel_AcquisitionMode,
)
from ome_types._autogenerated.ome_2016_06.channel_contrast_method import (
    Channel_ContrastMethod,
)
from ome_types._autogenerated.ome_2016_06.channel_illumination_type import (
    Channel_IlluminationType,
)
from ome_types._autogenerated.ome_2016_06.channel_ref import ChannelRef
from ome_types._autogenerated.ome_2016_06.comment_annotation import (
    CommentAnnotation,
)
from ome_types._autogenerated.ome_2016_06.dataset import Dataset
from ome_types._autogenerated.ome_2016_06.dataset_ref import DatasetRef
from ome_types._autogenerated.ome_2016_06.detector import Detector
from ome_types._autogenerated.ome_2016_06.detector_settings import (
    DetectorSettings,
)
from ome_types._autogenerated.ome_2016_06.detector_type import Detector_Type
from ome_types._autogenerated.ome_2016_06.dichroic import Dichroic
from ome_types._autogenerated.ome_2016_06.dichroic_ref import DichroicRef
from ome_types._autogenerated.ome_2016_06.double_annotation import (
    DoubleAnnotation,
)
from ome_types._autogenerated.ome_2016_06.ellipse import Ellipse
from ome_types._autogenerated.ome_2016_06.experiment import Experiment
from ome_types._autogenerated.ome_2016_06.experiment_ref import ExperimentRef
from ome_types._autogenerated.ome_2016_06.experiment_value import (
    Experiment_value,
)
from ome_types._autogenerated.ome_2016_06.experimenter import Experimenter
from ome_types._autogenerated.ome_2016_06.experimenter_group import (
    ExperimenterGroup,
)
from ome_types._autogenerated.ome_2016_06.experimenter_group_ref import (
    ExperimenterGroupRef,
)
from ome_types._autogenerated.ome_2016_06.experimenter_ref import (
    ExperimenterRef,
)
from ome_types._autogenerated.ome_2016_06.external import External
from ome_types._autogenerated.ome_2016_06.external_compression import (
    External_Compression,
)
from ome_types._autogenerated.ome_2016_06.filament import Filament
from ome_types._autogenerated.ome_2016_06.filament_type import Filament_Type
from ome_types._autogenerated.ome_2016_06.file_annotation import FileAnnotation
from ome_types._autogenerated.ome_2016_06.filter import Filter
from ome_types._autogenerated.ome_2016_06.filter_ref import FilterRef
from ome_types._autogenerated.ome_2016_06.filter_set import FilterSet
from ome_types._autogenerated.ome_2016_06.filter_set_ref import FilterSetRef
from ome_types._autogenerated.ome_2016_06.filter_type import Filter_Type
from ome_types._autogenerated.ome_2016_06.folder import Folder
from ome_types._autogenerated.ome_2016_06.folder_ref import FolderRef
from ome_types._autogenerated.ome_2016_06.generic_excitation_source import (
    GenericExcitationSource,
)
from ome_types._autogenerated.ome_2016_06.image import Image
from ome_types._autogenerated.ome_2016_06.image_ref import ImageRef
from ome_types._autogenerated.ome_2016_06.imaging_environment import (
    ImagingEnvironment,
)
from ome_types._autogenerated.ome_2016_06.instrument import Instrument
from ome_types._autogenerated.ome_2016_06.instrument_ref import InstrumentRef
from ome_types._autogenerated.ome_2016_06.label import Label
from ome_types._autogenerated.ome_2016_06.laser import Laser
from ome_types._autogenerated.ome_2016_06.laser_laser_medium import (
    Laser_LaserMedium,
)
from ome_types._autogenerated.ome_2016_06.laser_pulse import Laser_Pulse
from ome_types._autogenerated.ome_2016_06.laser_type import Laser_Type
from ome_types._autogenerated.ome_2016_06.leader import Leader
from ome_types._autogenerated.ome_2016_06.light_emitting_diode import (
    LightEmittingDiode,
)
from ome_types._autogenerated.ome_2016_06.light_path import LightPath
from ome_types._autogenerated.ome_2016_06.light_source import LightSource
from ome_types._autogenerated.ome_2016_06.light_source_settings import (
    LightSourceSettings,
)
from ome_types._autogenerated.ome_2016_06.line import Line
from ome_types._autogenerated.ome_2016_06.list_annotation import ListAnnotation
from ome_types._autogenerated.ome_2016_06.long_annotation import LongAnnotation
from ome_types._autogenerated.ome_2016_06.manufacturer_spec import (
    ManufacturerSpec,
)
from ome_types._autogenerated.ome_2016_06.map import Map
from ome_types._autogenerated.ome_2016_06.map_annotation import MapAnnotation
from ome_types._autogenerated.ome_2016_06.marker import Marker
from ome_types._autogenerated.ome_2016_06.mask import Mask
from ome_types._autogenerated.ome_2016_06.metadata_only import MetadataOnly
from ome_types._autogenerated.ome_2016_06.microbeam_manipulation import (
    MicrobeamManipulation,
)
from ome_types._autogenerated.ome_2016_06.microbeam_manipulation_ref import (
    MicrobeamManipulationRef,
)
from ome_types._autogenerated.ome_2016_06.microbeam_manipulation_value import (
    MicrobeamManipulation_value,
)
from ome_types._autogenerated.ome_2016_06.microscope import Microscope
from ome_types._autogenerated.ome_2016_06.microscope_type import (
    Microscope_Type,
)
from ome_types._autogenerated.ome_2016_06.naming_convention import (
    NamingConvention,
)
from ome_types._autogenerated.ome_2016_06.numeric_annotation import (
    NumericAnnotation,
)
from ome_types._autogenerated.ome_2016_06.objective import Objective
from ome_types._autogenerated.ome_2016_06.objective_correction import (
    Objective_Correction,
)
from ome_types._autogenerated.ome_2016_06.objective_immersion import (
    Objective_Immersion,
)
from ome_types._autogenerated.ome_2016_06.objective_settings import (
    ObjectiveSettings,
)
from ome_types._autogenerated.ome_2016_06.objective_settings_medium import (
    ObjectiveSettings_Medium,
)
from ome_types._autogenerated.ome_2016_06.ome import OME
from ome_types._autogenerated.ome_2016_06.pixel_type import PixelType
from ome_types._autogenerated.ome_2016_06.pixels import Pixels
from ome_types._autogenerated.ome_2016_06.pixels_dimension_order import (
    Pixels_DimensionOrder,
)
from ome_types._autogenerated.ome_2016_06.plane import Plane
from ome_types._autogenerated.ome_2016_06.plate import Plate
from ome_types._autogenerated.ome_2016_06.plate_acquisition import (
    PlateAcquisition,
)
from ome_types._autogenerated.ome_2016_06.point import Point
from ome_types._autogenerated.ome_2016_06.polygon import Polygon
from ome_types._autogenerated.ome_2016_06.polyline import Polyline
from ome_types._autogenerated.ome_2016_06.project import Project
from ome_types._autogenerated.ome_2016_06.project_ref import ProjectRef
from ome_types._autogenerated.ome_2016_06.pump import Pump
from ome_types._autogenerated.ome_2016_06.reagent import Reagent
from ome_types._autogenerated.ome_2016_06.reagent_ref import ReagentRef
from ome_types._autogenerated.ome_2016_06.rectangle import Rectangle
from ome_types._autogenerated.ome_2016_06.reference import Reference
from ome_types._autogenerated.ome_2016_06.rights import Rights
from ome_types._autogenerated.ome_2016_06.roi import ROI
from ome_types._autogenerated.ome_2016_06.roi_ref import ROIRef
from ome_types._autogenerated.ome_2016_06.screen import Screen
from ome_types._autogenerated.ome_2016_06.settings import Settings
from ome_types._autogenerated.ome_2016_06.shape import Shape
from ome_types._autogenerated.ome_2016_06.shape_fill_rule import Shape_FillRule
from ome_types._autogenerated.ome_2016_06.shape_font_family import (
    Shape_FontFamily,
)
from ome_types._autogenerated.ome_2016_06.shape_font_style import (
    Shape_FontStyle,
)
from ome_types._autogenerated.ome_2016_06.stage_label import StageLabel
from ome_types._autogenerated.ome_2016_06.structured_annotations import (
    StructuredAnnotations,
)
from ome_types._autogenerated.ome_2016_06.tag_annotation import TagAnnotation
from ome_types._autogenerated.ome_2016_06.term_annotation import TermAnnotation
from ome_types._autogenerated.ome_2016_06.text_annotation import TextAnnotation
from ome_types._autogenerated.ome_2016_06.tiff_data import TiffData
from ome_types._autogenerated.ome_2016_06.timestamp_annotation import (
    TimestampAnnotation,
)
from ome_types._autogenerated.ome_2016_06.transmittance_range import (
    TransmittanceRange,
)
from ome_types._autogenerated.ome_2016_06.type_annotation import TypeAnnotation
from ome_types._autogenerated.ome_2016_06.units_electric_potential import (
    UnitsElectricPotential,
)
from ome_types._autogenerated.ome_2016_06.units_frequency import UnitsFrequency
from ome_types._autogenerated.ome_2016_06.units_length import UnitsLength
from ome_types._autogenerated.ome_2016_06.units_power import UnitsPower
from ome_types._autogenerated.ome_2016_06.units_pressure import UnitsPressure
from ome_types._autogenerated.ome_2016_06.units_temperature import (
    UnitsTemperature,
)
from ome_types._autogenerated.ome_2016_06.units_time import UnitsTime
from ome_types._autogenerated.ome_2016_06.well import Well
from ome_types._autogenerated.ome_2016_06.well_sample import WellSample
from ome_types._autogenerated.ome_2016_06.well_sample_ref import WellSampleRef
from ome_types._autogenerated.ome_2016_06.xml_annotation import XMLAnnotation

__all__ = [
    "AffineTransform",
    "Annotation",
    "AnnotationRef",
    "Arc",
    "Arc_Type",
    "BasicAnnotation",
    "BinData",
    "BinData_Compression",
    "BinaryFile",
    "Binning",
    "BooleanAnnotation",
    "Channel",
    "Channel_AcquisitionMode",
    "Channel_ContrastMethod",
    "Channel_IlluminationType",
    "ChannelRef",
    "CommentAnnotation",
    "Dataset",
    "DatasetRef",
    "Detector",
    "DetectorSettings",
    "Detector_Type",
    "Dichroic",
    "DichroicRef",
    "DoubleAnnotation",
    "Ellipse",
    "Experiment",
    "ExperimentRef",
    "Experiment_value",
    "Experimenter",
    "ExperimenterGroup",
    "ExperimenterGroupRef",
    "ExperimenterRef",
    "External",
    "External_Compression",
    "Filament",
    "Filament_Type",
    "FileAnnotation",
    "Filter",
    "FilterRef",
    "FilterSet",
    "FilterSetRef",
    "Filter_Type",
    "Folder",
    "FolderRef",
    "GenericExcitationSource",
    "Image",
    "ImageRef",
    "ImagingEnvironment",
    "Instrument",
    "InstrumentRef",
    "Label",
    "Laser",
    "Laser_LaserMedium",
    "Laser_Pulse",
    "Laser_Type",
    "Leader",
    "LightEmittingDiode",
    "LightPath",
    "LightSource",
    "LightSourceSettings",
    "Line",
    "ListAnnotation",
    "LongAnnotation",
    "ManufacturerSpec",
    "Map",
    "MapAnnotation",
    "Marker",
    "Mask",
    "MetadataOnly",
    "MicrobeamManipulation",
    "MicrobeamManipulationRef",
    "MicrobeamManipulation_value",
    "Microscope",
    "Microscope_Type",
    "NamingConvention",
    "NumericAnnotation",
    "Objective",
    "Objective_Correction",
    "Objective_Immersion",
    "ObjectiveSettings",
    "ObjectiveSettings_Medium",
    "OME",
    "PixelType",
    "Pixels",
    "Pixels_DimensionOrder",
    "Plane",
    "Plate",
    "PlateAcquisition",
    "Point",
    "Polygon",
    "Polyline",
    "Project",
    "ProjectRef",
    "Pump",
    "Reagent",
    "ReagentRef",
    "Rectangle",
    "Reference",
    "Rights",
    "ROI",
    "ROIRef",
    "Screen",
    "Settings",
    "Shape",
    "Shape_FillRule",
    "Shape_FontFamily",
    "Shape_FontStyle",
    "StageLabel",
    "StructuredAnnotations",
    "TagAnnotation",
    "TermAnnotation",
    "TextAnnotation",
    "TiffData",
    "TimestampAnnotation",
    "TransmittanceRange",
    "TypeAnnotation",
    "UnitsElectricPotential",
    "UnitsFrequency",
    "UnitsLength",
    "UnitsPower",
    "UnitsPressure",
    "UnitsTemperature",
    "UnitsTime",
    "Well",
    "WellSample",
    "WellSampleRef",
    "XMLAnnotation",
]
