from ome_types._autogenerated.ome_2016_06.basic_annotation import (
    BasicAnnotation,
)
from xsdata_pydantic_basemodel.pydantic_compat import Field

__NAMESPACE__ = "http://www.openmicroscopy.org/Schemas/OME/2016-06"


class BooleanAnnotation(BasicAnnotation):
    """A simple boolean annotation of type xsd:boolean."""

    class Meta:
        namespace = "http://www.openmicroscopy.org/Schemas/OME/2016-06"

    value: bool = Field(
        metadata={
            "name": "Value",
            "type": "Element",
            "required": True,
        }
    )
