from pydantic import Field

from ome_types._autogenerated.ome_2016_06.text_annotation import TextAnnotation

__NAMESPACE__ = "http://www.openmicroscopy.org/Schemas/OME/2016-06"


class CommentAnnotation(TextAnnotation):
    """A simple comment annotation."""

    class Meta:
        namespace = "http://www.openmicroscopy.org/Schemas/OME/2016-06"

    value: str = Field(
        json_schema_extra={
            "name": "Value",
            "type": "Element",
            "required": True,
        }
    )
