from pydantic import Field

from ome_types._autogenerated.ome_2016_06.numeric_annotation import (
    NumericAnnotation,
)

__NAMESPACE__ = "http://www.openmicroscopy.org/Schemas/OME/2016-06"


class DoubleAnnotation(NumericAnnotation):
    """A simple numerical annotation of type xsd:double."""

    class Meta:
        namespace = "http://www.openmicroscopy.org/Schemas/OME/2016-06"

    value: float = Field(
        json_schema_extra={
            "name": "Value",
            "type": "Element",
            "required": True,
        }
    )
