from ome_types._autogenerated.ome_2016_06.binary_file import BinaryFile
from ome_types._autogenerated.ome_2016_06.type_annotation import TypeAnnotation
from xsdata_pydantic_basemodel.pydantic_compat import Field

__NAMESPACE__ = "http://www.openmicroscopy.org/Schemas/OME/2016-06"


class FileAnnotation(TypeAnnotation):
    """A file object annotation."""

    class Meta:
        namespace = "http://www.openmicroscopy.org/Schemas/OME/2016-06"

    binary_file: BinaryFile = Field(
        metadata={
            "name": "BinaryFile",
            "type": "Element",
            "required": True,
        }
    )
