from enum import Enum

__NAMESPACE__ = "http://www.openmicroscopy.org/Schemas/OME/2016-06"


class Laser_LaserMedium(Enum):
    CU = "Cu"
    AG = "Ag"
    AR_FL = "ArFl"
    AR_CL = "ArCl"
    KR_FL = "KrFl"
    KR_CL = "KrCl"
    XE_FL = "XeFl"
    XE_CL = "XeCl"
    XE_BR = "XeBr"
    N = "N"
    AR = "Ar"
    KR = "Kr"
    XE = "Xe"
    HE_NE = "HeNe"
    HE_CD = "HeCd"
    CO = "CO"
    CO2 = "CO2"
    H2_O = "H2O"
    HFL = "HFl"
    ND_GLASS = "NdGlass"
    ND_YAG = "NdYAG"
    ER_GLASS = "ErGlass"
    ER_YAG = "ErYAG"
    HO_YLF = "HoYLF"
    HO_YAG = "HoYAG"
    RUBY = "Ruby"
    TI_SAPPHIRE = "TiSapphire"
    ALEXANDRITE = "Alexandrite"
    RHODAMINE6_G = "Rhodamine6G"
    COUMARIN_C30 = "CoumarinC30"
    GA_AS = "GaAs"
    GA_AL_AS = "GaAlAs"
    EMINUS = "EMinus"
    OTHER = "Other"
