from ome_types._autogenerated.ome_2016_06.light_source import LightSource

__NAMESPACE__ = "http://www.openmicroscopy.org/Schemas/OME/2016-06"


class LightSourceGroup(LightSource):
    class Meta:
        namespace = "http://www.openmicroscopy.org/Schemas/OME/2016-06"
