from ome_types._autogenerated.ome_2016_06.annotation import Annotation
from ome_types._autogenerated.ome_2016_06.map import Map
from xsdata_pydantic_basemodel.pydantic_compat import Field

__NAMESPACE__ = "http://www.openmicroscopy.org/Schemas/OME/2016-06"


class MapAnnotation(Annotation):
    """An map annotation.

    The contents of this is a list of key/value pairs.
    """

    class Meta:
        namespace = "http://www.openmicroscopy.org/Schemas/OME/2016-06"

    value: Map = Field(
        metadata={
            "name": "Value",
            "type": "Element",
            "required": True,
        }
    )
