from ome_types._autogenerated.ome_2016_06.basic_annotation import (
    BasicAnnotation,
)

__NAMESPACE__ = "http://www.openmicroscopy.org/Schemas/OME/2016-06"


class NumericAnnotation(BasicAnnotation):
    """An abstract Numeric Annotation from which some others are derived."""
