from ome_types._autogenerated.ome_2016_06.shape import Shape

__NAMESPACE__ = "http://www.openmicroscopy.org/Schemas/OME/2016-06"


class ShapeGroup(Shape):
    class Meta:
        namespace = "http://www.openmicroscopy.org/Schemas/OME/2016-06"
