from pydantic import Field

from ome_types._autogenerated.ome_2016_06.basic_annotation import (
    BasicAnnotation,
)

__NAMESPACE__ = "http://www.openmicroscopy.org/Schemas/OME/2016-06"


class TermAnnotation(BasicAnnotation):
    """A ontology term annotation."""

    class Meta:
        namespace = "http://www.openmicroscopy.org/Schemas/OME/2016-06"

    value: str = Field(
        json_schema_extra={
            "name": "Value",
            "type": "Element",
            "required": True,
        }
    )
