from datetime import datetime

from ome_types._autogenerated.ome_2016_06.basic_annotation import (
    BasicAnnotation,
)
from xsdata_pydantic_basemodel.pydantic_compat import Field

__NAMESPACE__ = "http://www.openmicroscopy.org/Schemas/OME/2016-06"


class TimestampAnnotation(BasicAnnotation):
    """A date/time annotation of type xsd:dateTime."""

    class Meta:
        namespace = "http://www.openmicroscopy.org/Schemas/OME/2016-06"

    value: datetime = Field(
        metadata={
            "name": "Value",
            "type": "Element",
            "required": True,
        }
    )
