from ome_types._autogenerated.ome_2016_06.annotation import Annotation

__NAMESPACE__ = "http://www.openmicroscopy.org/Schemas/OME/2016-06"


class TypeAnnotation(Annotation):
    """An abstract Type Annotation from which some others are derived."""
