from typing import TYPE_CHECKING, cast

if TYPE_CHECKING:
    from typing import TypeAlias

    from ome_types._autogenerated.ome_2016_06 import (
        Arc,
        Filament,
        GenericExcitationSource,
        Instrument,
        Laser,
        LightEmittingDiode,
    )

    LightSource: TypeAlias = (
        GenericExcitationSource | LightEmittingDiode | Filament | Arc | Laser
    )


class InstrumentMixin:
    @property
    def light_source_group(self) -> list["LightSource"]:
        # here for backwards compatibility
        slf = cast("Instrument", self)
        return [
            *slf.arcs,
            *slf.filaments,
            *slf.generic_excitation_sources,
            *slf.lasers,
            *slf.light_emitting_diodes,
        ]
